package com.uimr.controller;

import com.uimr.dto.request.ReportRequest;
import com.uimr.model.Report;
import com.uimr.model.enums.ReportStatus;
import com.uimr.service.ReportService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/reports")
@RequiredArgsConstructor
public class ReportController {

    private final ReportService reportService;

    @GetMapping
    public ResponseEntity<List<Map<String, Object>>> getReports(Authentication auth) {
        return ResponseEntity.ok(reportService.getUserReports(auth.getName()).stream()
                .map(r -> Map.<String, Object>of(
                        "id", r.getId(),
                        "name", r.getName(),
                        "type", r.getType(),
                        "format", r.getFormat(),
                        "status", r.getStatus().name(),
                        "createdAt", r.getCreatedAt().toString(),
                        "fileUrl", r.getFileUrl() != null ? r.getFileUrl() : ""
                ))
                .collect(Collectors.toList()));
    }

    @PostMapping("/generate")
    public ResponseEntity<Report> generateReport(@RequestBody ReportRequest request, Authentication auth) {
        return ResponseEntity.ok(reportService.createReport(request, auth.getName()));
    }

    @GetMapping("/download/{id}")
    public ResponseEntity<byte[]> downloadReport(@PathVariable("id") Long id) {
        Report report = reportService.getReport(id);
        if (report.getStatus() != ReportStatus.READY) {
            return ResponseEntity.badRequest().build();
        }

        String content = "UIMR REPORT SUMMARY\n" +
                "Name: " + report.getName() + "\n" +
                "Type: " + report.getType() + "\n" +
                "Generated At: " + report.getCreatedAt() + "\n" +
                "Status: CONFIDENTIAL\n\n" +
                "This is a sample report generated by the UIMR Platform.";

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"report_" + id + ".txt\"")
                .contentType(MediaType.TEXT_PLAIN)
                .body(content.getBytes());
    }
}
